POST http://localhost:3000/api/activities
Content-Type: application/json

{
    "name": "Inliner"
}

###

POST http://localhost:3000/api/activities/oidcbvno67bx1nck8pzv5q50/items
Content-Type: application/json

{
    "name": "Helm",
    "category": "gear"
}

###

GET http://localhost:3000/api/activities

###

GET http://localhost:3000/api/activities/oidcbvno67bx1nck8pzv5q50/items

###

PATCH http://localhost:3000/api/activities/oidcbvno67bx1nck8pzv5q50/items/jq8dzgvhm64wkc8bcigo9ys3
Content-Type: application/json

{
    "name": "Fahrradhelm"
}

###

DELETE http://localhost:3000/api/activities/oidcbvno67bx1nck8pzv5q50