### Simple compilation request
POST http://localhost:3000/api/compile
Content-Type: application/json

{
    "tripname": "Testtrip",
    "tripstart": "2024-06-03",
    "tripend": "2024-06-05",
    "isAbroad": false,
    "accomodation": "clz1azi1b000qo0hvaa5kak18",
    "activities": [],
    "transport": "clz1azi2l007no0hvl57cq07l",
    "triptype": "clz1azi1x006no0hvlnkpgff3",
    "weather": []
}

### get accomodations
GET http://localhost:3000/api/accomodation

### Simplified Submit Request
POST http://localhost:3000/api/submitTasks
Content-Type: application/json

{
    "tripName": "Testtrip",
    "tripLength": 5,
    "tripBeginDate": "2023-08-18T08:00:00.000Z",
    "packingList": {
        "clothing": {
            "name": "Kleidung",
            "content": [
                {
                    "name": "Unterwäsche",
                    "dayMultiplier": 1
                },
                {
                    "name": "2x Socken lang / kurz",
                    "dayMultiplier": 1
                },
                {
                    "name": "Schlafshirt"
                },
                {
                    "name": "Schuhe"
                }
            ]
        },
        "toiletries": {
            "name": "Hygiene & Co.",
            "content": [
                {
                    "name": "Zahnbürste & Zahnpasta"
                },
                {
                    "name": "Duschgel"
                },
                {
                    "name": "Brillenetui"
                },
                {
                    "name": "Medikamente"
                }
            ]
        },
        "gear": {
            "name": "Ausrüstung",
            "content": []
        },
        "organisational": {
            "name": "Organisatorisches",
            "content": []
        },
        "entertainment": {
            "name": "Unterhaltung",
            "content": [
                {
                    "name": "Buch / eReader"
                }
            ]
        },
        "other": {
            "name": "sonstiges",
            "content": [
                {
                    "name": "Handyladekabel"
                }
            ]
        }
    }
}
###

PATCH http://localhost:3000/api/packinglists/cm0167zsu002ddlne3q0dftko/items/cm0167zsu001adlnexsylzga4
Content-Type: application/json

{
    "relevantForWeather": [
        "cold"
    ]
}